[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline';"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    Link = "</client/css/main.css>; rel=preload; as=style"

[[redirects]]
  from = "https://solovev.netlify.com/*"
  to = "https://solovev.one/:splat"
  status = 301
  force = true
