version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn run build
      - run: sudo apt install rsync
      - run: echo $KNOWN_HOSTS >> ~/.ssh/known_hosts
      - deploy:
          name: Deploy
          command: rsync -avzhe "ssh ${DEPLOY_SSH_PARAMS}" ./dist/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
