version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4a:0e:ac:f3:c7:5b:d2:e0:47:9f:53:46:ea:fe:e6:f5"
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Install gh-pages
          command: npm install gh-pages@2.0.1
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Git config user.email
          command: git config user.email "ivan@solovev.one"
      - run:
          name: Git config user.name
          command: git config user.name "Ivan Solovev"
      - run:
          name: Deploy project to gh-pages branch
          command: ./node_modules/.bin/gh-pages --dotfiles --message "[ci skip] Updates" --dist dist

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master

